runtime: go
api_version: go1

handlers:
  - url: /
    static_files: index.html
    upload: index.html
    secure: always
    login: required

  - url: /index.js
    static_files: index.js
    upload: index.js
    secure: always

  - url: /base64ArrayBuffer.js
    static_files: base64ArrayBuffer.js
    upload: base64ArrayBuffer.js
    secure: always

  - url: /elm.js
    static_files: build/elm.js
    upload: build/elm.js
    secure: always

  - url: /service-worker.js
    static_files: service-worker.js
    upload: service-worker.js
    secure: always

  - url: /.*
    login: required
    secure: always
    script: app.go
